package main

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"strings"
	"syscall"
	"text/tabwriter"
	"time"

	"costrict-router/internal/auth"
	"costrict-router/internal/config"
	"costrict-router/internal/i18n"
	"costrict-router/internal/ids"
	"costrict-router/internal/logx"
	"costrict-router/internal/proxy"
	"costrict-router/internal/server"
)

func main() {
	// 统一解析子命令并把错误收口到同一种用户可见输出。
	if len(os.Args) < 2 {
		usage()
		os.Exit(2)
	}
	var err error
	switch os.Args[1] {
	case "login":
		err = cmdLogin(os.Args[2:])
	case "serve":
		err = cmdServe(os.Args[2:])
	case "models":
		err = cmdModels(os.Args[2:])
	case "start":
		err = cmdStart(os.Args[2:])
	case "stop":
		err = cmdStop(os.Args[2:])
	case "status":
		err = cmdStatus(os.Args[2:])
	case "restart":
		err = cmdRestart(os.Args[2:])
	case "logs":
		err = cmdLogs(os.Args[2:])
	case "key":
		err = cmdKey(os.Args[2:])
	default:
		usage()
		os.Exit(2)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, i18n.T("Error:", "错误:"), err)
		os.Exit(1)
	}
}

func usage() {
	// 手写帮助信息，避免把仅测试用的隐藏参数暴露给普通用户。
	fmt.Fprintln(os.Stderr, i18n.T(`Usage:
  costrict-router login --base-url https://example.com
  costrict-router login --url <plugin-login-url>
  costrict-router serve [--addr 127.0.0.1:14567] [--debug]
  costrict-router models [--json]
  costrict-router start [--debug]
  costrict-router stop
  costrict-router status
  costrict-router restart
  costrict-router logs
  costrict-router key reset`, `用法:
  costrict-router login --base-url https://example.com
  costrict-router login --url <plugin-login-url>
  costrict-router serve [--addr 127.0.0.1:14567] [--debug]
  costrict-router models [--json]
  costrict-router start [--debug]
  costrict-router stop
  costrict-router status
  costrict-router restart
  costrict-router logs
  costrict-router key reset`))
}

func cmdLogin(args []string) error {
	// 登录命令负责生成或解析插件登录参数，轮询拿到 token 后写入本地配置。
	fs := flag.NewFlagSet("login", flag.ContinueOnError)
	baseURL := fs.String("base-url", "", i18n.T("CoStrict server base URL", "CoStrict 服务端地址"))
	loginURL := fs.String("url", "", i18n.T("login URL generated by plugin", "插件生成的登录 URL"))
	tokenFile := fs.String("token-file", "", i18n.T("import an existing token response JSON for testing", "导入已有 token 响应 JSON，仅用于测试"))
	configPath := fs.String("config", "", i18n.T("config file path", "配置文件路径"))
	timeout := fs.Duration("timeout", 5*time.Minute, i18n.T("login polling timeout", "登录轮询超时时间"))
	if err := fs.Parse(args); err != nil {
		return err
	}

	path, err := resolveConfigPath(*configPath)
	if err != nil {
		return err
	}
	cfg, err := config.Load(path)
	if err != nil {
		return err
	}

	if *tokenFile != "" {
		// token-file 只用于本地调试和自动化测试，不出现在正式用法说明里。
		if *baseURL == "" && *loginURL == "" && cfg.BaseURL == "" {
			return fmt.Errorf(i18n.T("--token-file requires --base-url or an existing base_url in config", "--token-file 需要配合 --base-url，或已有配置中存在 base_url"))
		}
		if *loginURL != "" {
			params, err := auth.ParseLoginURL(*loginURL)
			if err != nil {
				return err
			}
			cfg.ApplyLoginParams(params)
		} else if *baseURL != "" {
			cfg.BaseURL = strings.TrimRight(*baseURL, "/")
		}
		tf, err := config.ReadTokenFile(*tokenFile)
		if err != nil {
			return err
		}
		if cfg.State == "" {
			cfg.State = tf.State
		}
		if err := cfg.ApplyTokens(auth.Tokens{AccessToken: tf.AccessToken, RefreshToken: tf.RefreshToken, State: tf.State}); err != nil {
			return err
		}
		if err := cfg.Save(path); err != nil {
			return err
		}
		fmt.Printf(i18n.T("Token imported, config file: %s\n", "已导入 token，配置文件: %s\n"), path)
		fmt.Printf("base_url: %s\nuser_id: %s\naccess_token: %s\n", cfg.BaseURL, cfg.UserID, config.Redact(cfg.AccessToken))
		return nil
	}

	var params auth.LoginParams
	if *loginURL != "" {
		params, err = auth.ParseLoginURL(*loginURL)
		if err != nil {
			return err
		}
	} else {
		if *baseURL == "" {
			return fmt.Errorf(i18n.T("please provide --base-url or --url", "请提供 --base-url 或 --url"))
		}
		params = auth.LoginParams{
			BaseURL:     strings.TrimRight(*baseURL, "/"),
			MachineCode: validOrNewMachineCode(cfg.MachineCode),
			State:       auth.GenerateState(),
		}.WithDefaults()
	}
	cfg.ApplyLoginParams(params)
	client := auth.NewClient(cfg.AuthParams())
	url, err := client.BuildLoginURL()
	if err != nil {
		return err
	}
	fmt.Println(i18n.T("Open the following login URL in your browser, then keep this command waiting:", "请在浏览器打开以下登录 URL，完成登录后保持本命令等待："))
	fmt.Println(url)

	ctx, cancel := context.WithTimeout(context.Background(), *timeout)
	defer cancel()
	tokens, err := client.PollToken(ctx, 3*time.Second)
	if err != nil {
		return err
	}
	if err := client.CheckStatus(ctx, tokens.AccessToken); err != nil {
		return err
	}
	if err := cfg.ApplyTokens(tokens); err != nil {
		return err
	}
	if err := cfg.Save(path); err != nil {
		return err
	}
	fmt.Printf(i18n.T("Login succeeded, config file: %s\nuser_id: %s\naccess_token: %s\n", "登录成功，配置文件: %s\nuser_id: %s\naccess_token: %s\n"), path, cfg.UserID, config.Redact(cfg.AccessToken))
	return nil
}

func cmdServe(args []string) error {
	// serve 是前台服务入口，适合调试时直接查看日志和进程退出信息。
	fs := flag.NewFlagSet("serve", flag.ContinueOnError)
	addr := fs.String("addr", "", i18n.T("listen address", "监听地址"))
	configPath := fs.String("config", "", i18n.T("config file path", "配置文件路径"))
	debug := fs.Bool("debug", false, i18n.T("log forwarded request details", "记录转发请求详情"))
	logFile := fs.String("log-file", "", i18n.T("log file path", "日志文件路径"))
	noModels := fs.Bool("no-models", false, i18n.T("do not print model list on startup", "启动时不输出模型列表"))
	if err := fs.Parse(args); err != nil {
		return err
	}
	path, err := resolveConfigPath(*configPath)
	if err != nil {
		return err
	}
	cfg, err := config.Load(path)
	if err != nil {
		return err
	}
	if _, err := ensureLocalAPIKey(path, cfg, os.Stdout); err != nil {
		return err
	}
	logger, closeLogger, err := buildLogger(*logFile, *debug)
	if err != nil {
		return err
	}
	defer closeLogger()
	logger.Infof(i18n.T("Config file: %s", "配置文件: %s"), path)
	if *debug {
		logger.Warnf(i18n.T("debug is enabled; forwarded request summaries and truncated bodies will be logged with secrets redacted", "debug 已开启，将记录转发请求摘要和截断后的请求体，敏感认证信息会脱敏"))
	}
	if !*noModels {
		if err := printStartupModels(context.Background(), path, *cfg, logger, os.Stdout); err != nil {
			logger.Warnf(i18n.T("failed to fetch model list on startup: %v", "启动时获取模型列表失败: %v"), err)
		}
	}
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	return server.Run(ctx, path, *cfg, *addr, logger)
}

func cmdModels(args []string) error {
	// models 会先刷新即将过期的 token，再向上游拉取当前账号可用模型。
	fs := flag.NewFlagSet("models", flag.ContinueOnError)
	configPath := fs.String("config", "", i18n.T("config file path", "配置文件路径"))
	asJSON := fs.Bool("json", false, i18n.T("print raw JSON", "输出原始 JSON"))
	if err := fs.Parse(args); err != nil {
		return err
	}
	path, err := resolveConfigPath(*configPath)
	if err != nil {
		return err
	}
	cfg, err := config.Load(path)
	if err != nil {
		return err
	}
	logger := logx.New(io.Discard, false)
	svc := server.New(path, *cfg, logger)
	if err := svc.EnsureFreshToken(context.Background()); err != nil {
		return err
	}
	cfg = ptr(svc.Config())

	raw, err := fetchModels(context.Background(), *cfg)
	if err != nil {
		return err
	}
	if *asJSON {
		_, _ = os.Stdout.Write(raw)
		if len(raw) == 0 || raw[len(raw)-1] != '\n' {
			fmt.Println()
		}
		return nil
	}
	return printModels(raw)
}

type daemonState struct {
	PID        int       `json:"pid"`
	Addr       string    `json:"addr"`
	ConfigPath string    `json:"config_path"`
	LogPath    string    `json:"log_path"`
	StartedAt  time.Time `json:"started_at"`
}

func cmdStart(args []string) error {
	// start 负责拉起后台 serve 进程，写入 PID 文件并等待健康检查通过。
	fs := flag.NewFlagSet("start", flag.ContinueOnError)
	addr := fs.String("addr", "", i18n.T("listen address", "监听地址"))
	configPath := fs.String("config", "", i18n.T("config file path", "配置文件路径"))
	debug := fs.Bool("debug", false, i18n.T("log forwarded request details", "记录转发请求详情"))
	logPath := fs.String("log-file", "", i18n.T("log file path", "日志文件路径"))
	pidPath := fs.String("pid-file", "", i18n.T("PID file path", "PID 文件路径"))
	if err := fs.Parse(args); err != nil {
		return err
	}
	path, err := resolveConfigPath(*configPath)
	if err != nil {
		return err
	}
	cfg, err := config.Load(path)
	if err != nil {
		return err
	}
	if *addr == "" {
		*addr = cfg.ListenAddr
	}
	if *logPath == "" {
		*logPath, err = config.DefaultLogPath()
		if err != nil {
			return err
		}
	}
	if *pidPath == "" {
		*pidPath, err = config.DefaultPIDPath()
		if err != nil {
			return err
		}
	}
	if running, _ := readDaemonState(*pidPath); running.PID > 0 {
		// 已有 PID 时用健康检查确认真实存活，避免重复启动占用同一端口。
		if health, err := fetchHealth(running.Addr); err == nil {
			fmt.Printf(i18n.T("🟢 Service already running: http://%s/v1\n%s\n", "🟢 服务已在运行: http://%s/v1\n%s\n"), running.Addr, health)
			if cfg.LocalAPIKeyHash != "" {
				fmt.Println(i18n.T("Local API Key is already configured; if you lost it, run: costrict-router key reset", "本地 API Key 已配置；如已遗失，请执行: costrict-router key reset"))
			} else {
				fmt.Println(i18n.T("Local API Key is not configured for this config; restart the service to generate and enable one.", "当前配置尚未生成本地 API Key；请重启服务以生成并启用。"))
			}
			return nil
		}
	}
	if _, err := ensureLocalAPIKey(path, cfg, os.Stdout); err != nil {
		return err
	}

	exe, err := os.Executable()
	if err != nil {
		return err
	}
	childArgs := []string{"serve", "--config", path, "--addr", *addr, "--log-file", *logPath, "--no-models"}
	if *debug {
		childArgs = append(childArgs, "--debug")
	}
	if err := os.MkdirAll(filepath.Dir(*logPath), 0o700); err != nil {
		return err
	}
	logFile, err := os.OpenFile(*logPath, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o600)
	if err != nil {
		return err
	}
	defer logFile.Close()
	cmd := exec.Command(exe, childArgs...)
	cmd.Stdout = logFile
	cmd.Stderr = logFile
	detachProcess(cmd)
	if err := cmd.Start(); err != nil {
		return err
	}
	state := daemonState{
		PID:        cmd.Process.Pid,
		Addr:       *addr,
		ConfigPath: path,
		LogPath:    *logPath,
		StartedAt:  time.Now(),
	}
	if err := writeDaemonState(*pidPath, state); err != nil {
		_ = cmd.Process.Kill()
		return err
	}
	if err := waitForHealth(*addr, 10*time.Second); err != nil {
		_ = cmd.Process.Kill()
		_ = os.Remove(*pidPath)
		return fmt.Errorf(i18n.T("background process started but health check failed; check log %s: %w", "后台进程已启动但健康检查失败，请查看日志 %s: %w"), *logPath, err)
	}
	_ = cmd.Process.Release()
	fmt.Printf(i18n.T("🚀 Costrict Router started: http://%s/v1\n", "🚀 Costrict Router 已启动: http://%s/v1\n"), *addr)
	fmt.Printf(i18n.T("📄 Log file: %s\n", "📄 日志文件: %s\n"), *logPath)
	fmt.Printf(i18n.T("🧭 PID file: %s\n", "🧭 PID 文件: %s\n"), *pidPath)
	return nil
}

func cmdStop(args []string) error {
	// stop 优先走本地 shutdown 接口，失败时再按 PID 做兜底清理。
	fs := flag.NewFlagSet("stop", flag.ContinueOnError)
	pidPath := fs.String("pid-file", "", i18n.T("PID file path", "PID 文件路径"))
	if err := fs.Parse(args); err != nil {
		return err
	}
	path, err := resolvePIDPath(*pidPath)
	if err != nil {
		return err
	}
	state, err := readDaemonState(path)
	if err != nil {
		return err
	}
	if state.Addr != "" {
		req, _ := http.NewRequest(http.MethodPost, "http://"+state.Addr+"/-/shutdown", nil)
		resp, err := http.DefaultClient.Do(req)
		if err == nil {
			_ = resp.Body.Close()
			_ = os.Remove(path)
			fmt.Printf(i18n.T("🛑 Service stopped: %s\n", "🛑 服务已停止: %s\n"), state.Addr)
			return nil
		}
	}
	if state.PID > 0 {
		if proc, err := os.FindProcess(state.PID); err == nil {
			_ = proc.Kill()
		}
	}
	_ = os.Remove(path)
	fmt.Println(i18n.T("🛑 PID file removed; if the service is still running, check the process manually", "🛑 已清理 PID 文件；如服务仍在运行，请手动检查进程"))
	return nil
}

func cmdStatus(args []string) error {
	// status 通过 PID 文件定位服务，再访问 healthz 输出脱敏后的运行状态。
	fs := flag.NewFlagSet("status", flag.ContinueOnError)
	pidPath := fs.String("pid-file", "", i18n.T("PID file path", "PID 文件路径"))
	if err := fs.Parse(args); err != nil {
		return err
	}
	path, err := resolvePIDPath(*pidPath)
	if err != nil {
		return err
	}
	state, err := readDaemonState(path)
	if err != nil {
		return err
	}
	health, err := fetchHealth(state.Addr)
	if err != nil {
		return fmt.Errorf(i18n.T("🔴 Service unavailable, PID=%d addr=%s: %w", "🔴 服务不可用，PID=%d addr=%s: %w"), state.PID, state.Addr, err)
	}
	fmt.Printf(i18n.T("🟢 Service running: http://%s/v1\n", "🟢 服务运行中: http://%s/v1\n"), state.Addr)
	fmt.Printf(i18n.T("PID: %d\nLog: %s\nStarted at: %s\n", "PID: %d\n日志: %s\n启动时间: %s\n"), state.PID, state.LogPath, state.StartedAt.Format(time.RFC3339))
	fmt.Println(health)
	return nil
}

func cmdRestart(args []string) error {
	// restart 复用 stop 和 start 的参数组装逻辑，保证行为与单独命令一致。
	fs := flag.NewFlagSet("restart", flag.ContinueOnError)
	addr := fs.String("addr", "", i18n.T("listen address", "监听地址"))
	configPath := fs.String("config", "", i18n.T("config file path", "配置文件路径"))
	debug := fs.Bool("debug", false, i18n.T("log forwarded request details", "记录转发请求详情"))
	logPath := fs.String("log-file", "", i18n.T("log file path", "日志文件路径"))
	pidPath := fs.String("pid-file", "", i18n.T("PID file path", "PID 文件路径"))
	if err := fs.Parse(args); err != nil {
		return err
	}
	stopArgs := []string{}
	if *pidPath != "" {
		stopArgs = append(stopArgs, "--pid-file", *pidPath)
	}
	if err := cmdStop(stopArgs); err != nil {
		fmt.Printf(i18n.T("⚠️  Failed to stop old service, continuing to start: %v\n", "⚠️  停止旧服务失败，继续尝试启动: %v\n"), err)
	}
	startArgs := []string{}
	if *addr != "" {
		startArgs = append(startArgs, "--addr", *addr)
	}
	if *configPath != "" {
		startArgs = append(startArgs, "--config", *configPath)
	}
	if *logPath != "" {
		startArgs = append(startArgs, "--log-file", *logPath)
	}
	if *pidPath != "" {
		startArgs = append(startArgs, "--pid-file", *pidPath)
	}
	if *debug {
		startArgs = append(startArgs, "--debug")
	}
	return cmdStart(startArgs)
}

func cmdLogs(args []string) error {
	// logs 先打印最后 N 行历史日志，再持续跟随新增内容直到用户中断。
	fs := flag.NewFlagSet("logs", flag.ContinueOnError)
	logPath := fs.String("log-file", "", i18n.T("log file path", "日志文件路径"))
	lines := fs.Int("n", 1000, i18n.T("show last N lines before following", "开始跟随前显示最近 N 行"))
	plain := fs.Bool("plain", false, i18n.T("strip ANSI colors", "去除 ANSI 高亮"))
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *logPath == "" {
		var err error
		*logPath, err = config.DefaultLogPath()
		if err != nil {
			return err
		}
	}
	offset, content, err := tailLinesWithOffset(*logPath, *lines)
	if err != nil {
		return err
	}
	if *plain {
		content = logx.StripANSI(content)
	}
	fmt.Print(content)
	return followLog(*logPath, offset, *plain)
}

func cmdKey(args []string) error {
	if len(args) < 1 {
		return fmt.Errorf(i18n.T("usage: costrict-router key reset [--config path]", "用法: costrict-router key reset [--config path]"))
	}
	switch args[0] {
	case "reset":
		return cmdKeyReset(args[1:])
	default:
		return fmt.Errorf(i18n.T("unknown key command: %s", "未知 key 命令: %s"), args[0])
	}
}

func cmdKeyReset(args []string) error {
	fs := flag.NewFlagSet("key reset", flag.ContinueOnError)
	configPath := fs.String("config", "", i18n.T("config file path", "配置文件路径"))
	if err := fs.Parse(args); err != nil {
		return err
	}
	path, err := resolveConfigPath(*configPath)
	if err != nil {
		return err
	}
	cfg, err := config.Load(path)
	if err != nil {
		return err
	}
	apiKey, err := resetLocalAPIKey(path, cfg)
	if err != nil {
		return err
	}
	fmt.Printf(i18n.T("Local API Key reset. Save it now; it will not be shown again:\n%s\n", "本地 API Key 已重置。请立即保存，它不会再次显示：\n%s\n"), apiKey)
	fmt.Printf(i18n.T("Config file: %s\n", "配置文件: %s\n"), path)
	if pidPath, err := config.DefaultPIDPath(); err == nil {
		if state, err := readDaemonState(pidPath); err == nil && state.ConfigPath == path {
			fmt.Printf(i18n.T("A service using this config appears to be running at http://%s/v1; restart it for the new key to take effect.\n", "检测到使用该配置的服务可能正在运行: http://%s/v1；请重启服务后新 key 才会生效。\n"), state.Addr)
		}
	}
	return nil
}

func fetchModels(ctx context.Context, cfg config.Config) ([]byte, error) {
	// 直接请求 CoStrict 模型列表接口，供 models 命令和前台启动提示复用。
	base, err := url.Parse(strings.TrimRight(cfg.BaseURL, "/"))
	if err != nil {
		return nil, err
	}
	base.Path = "/ai-gateway/api/v1/models"
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, base.String(), nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Authorization", "Bearer "+cfg.AccessToken)
	req.Header.Set("X-Request-ID", ids.UUID())
	req.Header.Set("x-user-id", cfg.UserID)
	req.Header.Set("User-Agent", "costrict-router/"+proxy.Version)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf(i18n.T("failed to fetch models: HTTP %d %s", "获取模型失败: HTTP %d %s"), resp.StatusCode, string(body))
	}
	return body, nil
}

func printStartupModels(ctx context.Context, configPath string, cfg config.Config, logger *logx.Logger, out io.Writer) error {
	if out == nil {
		out = io.Discard
	}
	svc := server.New(configPath, cfg, logger)
	if err := svc.EnsureFreshToken(ctx); err != nil {
		return err
	}
	raw, err := fetchModels(ctx, svc.Config())
	if err != nil {
		return err
	}
	fmt.Fprintln(out, i18n.T("\n📚 Available models", "\n📚 可用模型"))
	return printModelsTo(out, raw)
}

func printModels(raw []byte) error {
	return printModelsTo(os.Stdout, raw)
}

func printModelsTo(out io.Writer, raw []byte) error {
	// 将上游 JSON 响应整理成终端表格，避免用户直接阅读完整原始响应。
	var payload struct {
		Data []struct {
			ID                  string `json:"id"`
			ContextWindow       int    `json:"contextWindow"`
			MaxTokens           int    `json:"maxTokens"`
			SupportsImages      bool   `json:"supportsImages"`
			SupportsComputerUse bool   `json:"supportsComputerUse"`
		} `json:"data"`
	}
	if err := json.NewDecoder(bytes.NewReader(raw)).Decode(&payload); err != nil {
		return err
	}
	tw := tabwriter.NewWriter(out, 0, 0, 2, ' ', 0)
	fmt.Fprintln(tw, "MODEL\tCONTEXT\tMAX_TOKENS\tIMAGE\tCOMPUTER_USE")
	for _, model := range payload.Data {
		fmt.Fprintf(tw, "%s\t%d\t%d\t%t\t%t\n", model.ID, model.ContextWindow, model.MaxTokens, model.SupportsImages, model.SupportsComputerUse)
	}
	return tw.Flush()
}

func buildLogger(logFile string, debug bool) (*logx.Logger, func(), error) {
	if logFile == "" {
		return logx.New(os.Stderr, debug), func() {}, nil
	}
	logger, err := logx.NewFile(logFile, debug)
	if err != nil {
		return nil, func() {}, err
	}
	return logger, func() { _ = logger.Close() }, nil
}

func ensureLocalAPIKey(path string, cfg *config.Config, out io.Writer) (string, error) {
	if cfg.LocalAPIKeyHash != "" {
		return "", nil
	}
	apiKey, err := resetLocalAPIKey(path, cfg)
	if err != nil {
		return "", err
	}
	if out != nil {
		fmt.Fprintf(out, i18n.T("Local API Key generated. Save it now; it will not be shown again:\n%s\n", "已生成本地 API Key。请立即保存，它不会再次显示：\n%s\n"), apiKey)
	}
	return apiKey, nil
}

func resetLocalAPIKey(path string, cfg *config.Config) (string, error) {
	apiKey, err := config.GenerateLocalAPIKey()
	if err != nil {
		return "", err
	}
	if err := cfg.SetLocalAPIKey(apiKey); err != nil {
		return "", err
	}
	if err := cfg.Save(path); err != nil {
		return "", err
	}
	return apiKey, nil
}

func resolvePIDPath(path string) (string, error) {
	if path != "" {
		return path, nil
	}
	return config.DefaultPIDPath()
}

func readDaemonState(path string) (daemonState, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return daemonState{}, fmt.Errorf(i18n.T("failed to read PID file: %w", "读取 PID 文件失败: %w"), err)
	}
	var state daemonState
	if err := json.Unmarshal(data, &state); err != nil {
		return daemonState{}, err
	}
	if state.PID <= 0 || state.Addr == "" {
		return daemonState{}, fmt.Errorf(i18n.T("invalid PID file content: %s", "PID 文件内容无效: %s"), path)
	}
	return state, nil
}

func writeDaemonState(path string, state daemonState) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	data, err := json.MarshalIndent(state, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o600)
}

func waitForHealth(addr string, timeout time.Duration) error {
	deadline := time.Now().Add(timeout)
	var lastErr error
	for time.Now().Before(deadline) {
		if _, err := fetchHealth(addr); err == nil {
			return nil
		} else {
			lastErr = err
		}
		time.Sleep(200 * time.Millisecond)
	}
	if lastErr != nil {
		return lastErr
	}
	return fmt.Errorf(i18n.T("health check timed out", "健康检查超时"))
}

func fetchHealth(addr string) (string, error) {
	resp, err := http.Get("http://" + addr + "/healthz")
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return "", fmt.Errorf("HTTP %d %s", resp.StatusCode, string(body))
	}
	var pretty bytes.Buffer
	if json.Indent(&pretty, body, "", "  ") == nil {
		return pretty.String(), nil
	}
	return string(body), nil
}

func tailLinesWithOffset(path string, n int) (int64, string, error) {
	if n <= 0 {
		n = 1000
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return 0, "", err
	}
	text := string(data)
	lines := strings.SplitAfter(text, "\n")
	if len(lines) > n {
		lines = lines[len(lines)-n:]
	}
	return int64(len(data)), strings.Join(lines, ""), nil
}

func followLog(path string, offset int64, plain bool) error {
	// 用轻量轮询实现跨平台 tail -f，同时处理日志轮转导致的文件截断。
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	ticker := time.NewTicker(500 * time.Millisecond)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return nil
		case <-ticker.C:
			info, err := os.Stat(path)
			if err != nil {
				return err
			}
			if info.Size() < offset {
				offset = 0
			}
			if info.Size() == offset {
				continue
			}
			file, err := os.Open(path)
			if err != nil {
				return err
			}
			if _, err := file.Seek(offset, io.SeekStart); err != nil {
				_ = file.Close()
				return err
			}
			chunk, err := io.ReadAll(file)
			_ = file.Close()
			if err != nil {
				return err
			}
			offset = info.Size()
			text := string(chunk)
			if plain {
				text = logx.StripANSI(text)
			}
			fmt.Print(text)
		}
	}
}

func resolveConfigPath(path string) (string, error) {
	if path != "" {
		return path, nil
	}
	return config.DefaultPath()
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if value != "" {
			return value
		}
	}
	return ""
}

func validOrNewMachineCode(value string) string {
	if auth.ValidMachineCode(value) {
		return value
	}
	return auth.GenerateMachineCode()
}

func ptr[T any](v T) *T {
	return &v
}
